import { NotesConfig } from "src/types";
import graphImage from "src/assets/images/notes/exampleGraph.webp";

export const notesConfig: NotesConfig[] = [
  {
    sectionHeading: "Morning prep",
    content: [
      {
        title: "Morning Notes",
        description: `If you are committed to this business, discipline is key. Build yourself a routine. Stick to it. Interpreting the morning levels, prep for the day (knowing in advance where my trades could be) and sharing my morning notes is my daily routine. BE DISCIPLINED! If you are committed to this business, discipline is key. Build yourself a routine. Stick to it. Interpreting the morning levels, prep for the day (knowing in advance where my trades could be) and sharing my morning notes is my daily routine. BE DISCIPLINED! If you are committed to this business, discipline is key. Build yourself a routine. Stick to it. Interpreting the morning levels, prep for the day (knowing in advance where my trades could be) and sharing my morning notes is my daily routine. BE DISCIPLINED! If you are committed to this business, discipline is key. Build yourself a routine. Stick to it. Interpreting the morning levels, prep for the day (knowing in advance where my trades could be) and sharing my morning notes is my daily routine. BE DISCIPLINED! If you are committed to this business, discipline is key. Build yourself a routine. Stick to it. Interpreting the morning levels, prep for the day (knowing in advance where my trades could be) and sharing my morning notes is my daily routine. BE DISCIPLINED! If you are committed to this business, discipline is key. Build yourself a routine. Stick to it. Interpreting the morning levels, prep for the day (knowing in advance where my trades could be) and sharing my morning notes is my daily routine. BE DISCIPLINED!`,
        image: graphImage,
        alt: "abc graph",
      },
      {
        title: "Morning Notes",
        description: `If you are committed to this business, discipline is key. Build yourself a routine. Stick to it. Interpreting the morning levels, prep for the day (knowing in advance where my trades could be) and sharing my morning notes is my daily routine. BE DISCIPLINED! If you are committed to this business, discipline is key. Build yourself a routine. Stick to it. Interpreting the morning levels, prep for the day (knowing in advance where my trades could be) and sharing my morning notes is my daily routine. BE DISCIPLINED! If you are committed to this business, discipline is key. Build yourself a routine. Stick to it. Interpreting the morning levels, prep for the day (knowing in advance where my trades could be) and sharing my morning notes is my daily routine. BE DISCIPLINED! If you are committed to this business, discipline is key. Build yourself a routine. Stick to it. Interpreting the morning levels, prep for the day (knowing in advance where my trades could be) and sharing my morning notes is my daily routine. BE DISCIPLINED! If you are committed to this business, discipline is key. Build yourself a routine. Stick to it. Interpreting the morning levels, prep for the day (knowing in advance where my trades could be) and sharing my morning notes is my daily routine. BE DISCIPLINED! If you are committed to this business, discipline is key. Build yourself a routine. Stick to it. Interpreting the morning levels, prep for the day (knowing in advance where my trades could be) and sharing my morning notes is my daily routine. BE DISCIPLINED!`,
        image: graphImage,
        alt: "abc graph",
      },
      {
        title: "Morning Notes",
        description: `If you are committed to this business, discipline is key. Build yourself a routine. Stick to it. Interpreting the morning levels, prep for the day (knowing in advance where my trades could be) and sharing my morning notes is my daily routine. BE DISCIPLINED! If you are committed to this business, discipline is key. Build yourself a routine. Stick to it. Interpreting the morning levels, prep for the day (knowing in advance where my trades could be) and sharing my morning notes is my daily routine. BE DISCIPLINED! If you are committed to this business, discipline is key. Build yourself a routine. Stick to it. Interpreting the morning levels, prep for the day (knowing in advance where my trades could be) and sharing my morning notes is my daily routine. BE DISCIPLINED! If you are committed to this business, discipline is key. Build yourself a routine. Stick to it. Interpreting the morning levels, prep for the day (knowing in advance where my trades could be) and sharing my morning notes is my daily routine. BE DISCIPLINED! If you are committed to this business, discipline is key. Build yourself a routine. Stick to it. Interpreting the morning levels, prep for the day (knowing in advance where my trades could be) and sharing my morning notes is my daily routine. BE DISCIPLINED! If you are committed to this business, discipline is key. Build yourself a routine. Stick to it. Interpreting the morning levels, prep for the day (knowing in advance where my trades could be) and sharing my morning notes is my daily routine. BE DISCIPLINED!`,
        image: graphImage,
        alt: "abc graph",
      },
      {
        title: "Morning Notes",
        description: `If you are committed to this business, discipline is key. Build yourself a routine. Stick to it. Interpreting the morning levels, prep for the day (knowing in advance where my trades could be) and sharing my morning notes is my daily routine. BE DISCIPLINED! If you are committed to this business, discipline is key. Build yourself a routine. Stick to it. Interpreting the morning levels, prep for the day (knowing in advance where my trades could be) and sharing my morning notes is my daily routine. BE DISCIPLINED! If you are committed to this business, discipline is key. Build yourself a routine. Stick to it. Interpreting the morning levels, prep for the day (knowing in advance where my trades could be) and sharing my morning notes is my daily routine. BE DISCIPLINED! If you are committed to this business, discipline is key. Build yourself a routine. Stick to it. Interpreting the morning levels, prep for the day (knowing in advance where my trades could be) and sharing my morning notes is my daily routine. BE DISCIPLINED! If you are committed to this business, discipline is key. Build yourself a routine. Stick to it. Interpreting the morning levels, prep for the day (knowing in advance where my trades could be) and sharing my morning notes is my daily routine. BE DISCIPLINED! If you are committed to this business, discipline is key. Build yourself a routine. Stick to it. Interpreting the morning levels, prep for the day (knowing in advance where my trades could be) and sharing my morning notes is my daily routine. BE DISCIPLINED!`,
        image: graphImage,
        alt: "abc graph",
      },
      {
        title: "Morning Notes",
        description: `If you are committed to this business, discipline is key. Build yourself a routine. Stick to it. Interpreting the morning levels, prep for the day (knowing in advance where my trades could be) and sharing my morning notes is my daily routine. BE DISCIPLINED! If you are committed to this business, discipline is key. Build yourself a routine. Stick to it. Interpreting the morning levels, prep for the day (knowing in advance where my trades could be) and sharing my morning notes is my daily routine. BE DISCIPLINED! If you are committed to this business, discipline is key. Build yourself a routine. Stick to it. Interpreting the morning levels, prep for the day (knowing in advance where my trades could be) and sharing my morning notes is my daily routine. BE DISCIPLINED! If you are committed to this business, discipline is key. Build yourself a routine. Stick to it. Interpreting the morning levels, prep for the day (knowing in advance where my trades could be) and sharing my morning notes is my daily routine. BE DISCIPLINED! If you are committed to this business, discipline is key. Build yourself a routine. Stick to it. Interpreting the morning levels, prep for the day (knowing in advance where my trades could be) and sharing my morning notes is my daily routine. BE DISCIPLINED! If you are committed to this business, discipline is key. Build yourself a routine. Stick to it. Interpreting the morning levels, prep for the day (knowing in advance where my trades could be) and sharing my morning notes is my daily routine. BE DISCIPLINED!`,
        image: graphImage,
        alt: "abc graph",
      },
    ],
  },
];
